"""Serving deterministic results that are too slow to compute on request.

The API is a pure function of its inputs -- that is stated at the top of
`api/main.py` and it is what makes this possible.  A result that cannot change
between identical requests does not have to be recomputed for each one.

It has to be done because the game-theory modules are slow in a way serverless
hosting cannot accommodate:

    geographic, simulate, equity      under a second
    rejoin_validation                 ~2 s
    phasing                           ~12 s
    joint_game                        ~70 s
    bargaining                        ~100 s

Vercel caps a function at 10 s on the free tier and 60 s by default on Pro, so
the last three would return a gateway timeout on every plan.  They are the
three newest and most interesting results in the study, so losing them is not
an option, and making them faster is not honest -- the cost is real work
(hundreds of equilibria behind each bargaining sweep), not waste.

So they are computed once, written to `data/precomputed/`, committed, and
served from there.  Locally, deleting the directory restores live computation,
which is what makes this a cache rather than a fork of the results.

Staleness is the obvious danger.  A committed JSON file that no longer matches
the model it came from is precisely this codebase's characteristic failure: a
plausible number, served confidently, with nothing raising.  Two guards:

  * every file records the model fingerprint it was generated against, and
    `load` refuses a file whose fingerprint does not match the running config;
  * a test recomputes each entry and compares, so a model change that would
    invalidate a file fails CI rather than shipping.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any, Callable, Dict, Optional

from .config import Config

DIR = Path(__file__).resolve().parent.parent / "data" / "precomputed"

# Only entries a request cannot vary.  Anything taking a user-supplied
# parameter is computed live, because precomputing a grid would either be
# enormous or silently snap a request to a neighbouring value.
ENTRIES = ("rejoin", "phasing", "bargaining", "joint", "joint_optimum",
           "gate_dependence")


def fingerprint(cfg: Optional[Config] = None) -> str:
    """A short hash of every parameter the precomputed results depend on.

    The whole config rather than a hand-picked subset: picking a subset means
    deciding in advance which parameters matter, and being wrong about that is
    exactly how a stale file survives. A parameter that turns out not to affect
    a result costs only an unnecessary regeneration.
    """
    cfg = cfg or Config()
    payload = json.dumps(cfg.to_dict(), sort_keys=True, default=str)
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()[:16]


def path_for(name: str) -> Path:
    return DIR / f"{name}.json"


def load(name: str, cfg: Optional[Config] = None) -> Optional[dict]:
    """Return the precomputed result, or None to compute live.

    None on a missing file, on unreadable JSON, and on a fingerprint mismatch.
    Returning None rather than raising is deliberate: a stale or absent cache
    should make the API slower, never wrong, and never down.
    """
    p = path_for(name)
    if not p.exists():
        return None
    try:
        with open(p, encoding="utf-8") as fh:
            blob = json.load(fh)
    except (json.JSONDecodeError, OSError):
        return None
    if blob.get("_fingerprint") != fingerprint(cfg):
        return None
    return blob.get("result")


def serve(name: str, compute: Callable[[], dict], cfg: Optional[Config] = None) -> dict:
    """Precomputed result if it is valid, otherwise compute it now.

    The returned payload carries `_source` so a reader can tell which happened.
    That matters for a study whose whole discipline is provenance: a number
    served from a file and a number computed on the spot are the same number
    only if the guards above held, and the reader is entitled to see which one
    they are looking at.
    """
    hit = load(name, cfg)
    if hit is not None:
        return {**hit, "_source": "precomputed"}
    result = compute()
    return {**result, "_source": "computed"}


def write(name: str, result: dict, cfg: Optional[Config] = None) -> Path:
    """Write one precomputed entry, stamped with its fingerprint."""
    DIR.mkdir(parents=True, exist_ok=True)
    p = path_for(name)
    blob = {
        "_fingerprint": fingerprint(cfg),
        "_entry": name,
        "_note": (
            "Generated by scripts/precompute.py. Do not hand-edit. Delete this "
            "directory to restore live computation. The fingerprint is a hash "
            "of the full model config; a mismatch makes the loader fall back "
            "to computing rather than serve a stale answer."
        ),
        "result": result,
    }
    with open(p, "w", encoding="utf-8") as fh:
        json.dump(blob, fh, separators=(",", ":"))
    return p


def status(cfg: Optional[Config] = None) -> dict:
    """What is cached, and whether it is still valid.  Exposed on /api/meta."""
    cfg = cfg or Config()
    fp = fingerprint(cfg)
    rows = []
    for name in ENTRIES:
        p = path_for(name)
        state = "missing"
        size = None
        if p.exists():
            size = p.stat().st_size
            state = "valid" if load(name, cfg) is not None else "stale"
        rows.append({"entry": name, "state": state, "bytes": size})
    return {
        "fingerprint": fp,
        "entries": rows,
        "all_valid": all(r["state"] == "valid" for r in rows),
        "note": (
            "Entries are served from disk when valid and computed live "
            "otherwise. A stale entry is never served."
        ),
    }
